#!/usr/bin/php
<?php

require('config.inc.php');
require('classes/Content.class.php');
$ROOT_URI = 'https://www.studentrobotics.org/~ckirkham/srweb/';

$newsItems = array();

if ($d = opendir(CONTENT_DIR . '/news')){

	while (false !== ($file = readdir($d))){

		if (($file != '.') && ($file != '..')){

			$newsItems[] = new Content(CONTENT_DIR . '/news/' . $file);

		}//if

	}//while

	closedir($d);

	if (count($newsItems) > 0){

		$output  = "<?xml version='1.0'?><rss version='2.0'><channel>";
		$output .= "<title>Student Robotics Latest News</title>";
		$output .= "<link>" . $ROOT_URI . "news/</link>";
		$output .= "<lastBuildDate>" . date(DATE_RSS) . "</lastBuildDate>";
		$output .= "<description>All the latest news from Student Robotics</description>";

		usort($newsItems, "dateStrCmp");

		foreach ($newsItems as $newsItem){

			$output .= "<item>";

			$output .= "<title>" . $newsItem->getMeta('TITLE') . "</title>";
			$output .= "<link>" . $ROOT_URI . str_replace(CONTENT_DIR . '/', '', $newsItem->filename) . "</link>";
			$output .= "<guid>" . $ROOT_URI . str_replace(CONTENT_DIR . '/', '', $newsItem->filename) . "</guid>";
			$output .= "<description>" . $newsItem->getMeta('DESCRIPTION') . "</description>";
			$output .= "<pubDate>" . date(DATE_RSS, strtotime($newsItem->getPubDate())) . "</pubDate>";

			$output .= "</item>";

		}//foreach

		$output .= "</channel></rss>";

		if (!file_exists('feed.rss'))
			touch('feed.rss');

		$f = fopen('feed.rss', 'w');
		fwrite($f, $output);
		fclose($f);

		echo "File 'feed.rss' written\n";

	} else {

		echo "Nothing to write\n";

	}

} else {

	echo "ERROR opening directory 'content/news/ '\n";

}


function dateStrCmp($a, $b){

	if (strtotime($a->getPubDate()) == strtotime($b->getPubDate()))
		return 0;

	return strtotime($a->getPubDate()) > strtotime($b->getPubDate()) ? -1 : 1;

}//dateStrCmp


?>